# Generated by Django 5.0 on 2024-01-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('review', models.CharField(max_length=500)),
                ('image', models.ImageField(default='', upload_to='img/')),
            ],
        ),
    ]
