# Generated by Django 5.0 on 2024-01-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_testimonial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
