# Generated by Django 5.0 on 2024-01-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_rename_services_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
