# Generated by Django 5.0 on 2024-01-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_service_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=200)),
                ('pay', models.CharField(max_length=200)),
                ('job_type', models.BooleanField()),
                ('location', models.CharField(max_length=500)),
                ('job_discription', models.CharField(max_length=900)),
                ('application_deadline', models.DateField()),
                ('positions', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='short_disc',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='service',
            name='content',
            field=models.CharField(max_length=2000),
        ),
    ]
