# Generated by Django 5.0 on 2024-01-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_jobs_service_short_disc_alter_service_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs',
            new_name='Job',
        ),
    ]
