# Generated by Django 5.0 on 2024-01-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_rename_jobs_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='application_deadline',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='positions',
            field=models.CharField(max_length=200),
        ),
    ]
