# Generated by Django 5.0 on 2024-01-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_job_application_deadline_alter_job_job_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.ImageField(default='', upload_to='img/')),
                ('short_disc', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=2000)),
                ('image', models.ImageField(default='', upload_to='img/')),
                ('url', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
