# Generated by Django 5.0 on 2024-01-22 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_technology'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyDetails',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='url',
        ),
    ]
