# Generated by Django 5.0 on 2024-01-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_delete_companydetails_remove_technology_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(max_length=50)),
                ('com_discription', models.CharField(default='', max_length=200)),
                ('com_info', models.CharField(blank=True, max_length=400)),
                ('com_logo', models.ImageField(default='', upload_to='img/')),
                ('com_email', models.CharField(blank=True, default='', max_length=400)),
                ('com_location_1', models.CharField(blank=True, default='', max_length=400)),
                ('com_location_2', models.CharField(blank=True, default='', max_length=400)),
                ('com_location_3', models.CharField(blank=True, default='', max_length=400)),
                ('com_location_4', models.CharField(blank=True, default='', max_length=400)),
                ('com_phone', models.CharField(blank=True, default='', max_length=400)),
                ('com_facebook', models.CharField(blank=True, default='', max_length=400)),
                ('com_linkedin', models.CharField(blank=True, default='', max_length=400)),
                ('com_instagram', models.CharField(blank=True, default='', max_length=400)),
                ('com_slack', models.CharField(blank=True, default='', max_length=400)),
                ('com_skype', models.CharField(blank=True, default='', max_length=400)),
                ('com_youtube', models.CharField(blank=True, default='', max_length=400)),
            ],
        ),
    ]
